"""empty message

Revision ID: 49809608418c
Revises: 79e8f3ebaf11
Create Date: 2022-01-07 11:47:40.431797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49809608418c'
down_revision = '79e8f3ebaf11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Resolutions', sa.Column('ext', sa.String(length=10), nullable=True))
    op.add_column('Video', sa.Column('title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Video', 'title')
    op.drop_column('Resolutions', 'ext')
    # ### end Alembic commands ###
