"""empty message

Revision ID: 88f5db6a131c
Revises: 76e2f68a5bc0
Create Date: 2021-12-22 12:20:16.126365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88f5db6a131c'
down_revision = '76e2f68a5bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Video', sa.Column('dw_date', sa.String(length=50), nullable=True))
    op.drop_column('Video', 'download_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Video', sa.Column('download_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('Video', 'dw_date')
    # ### end Alembic commands ###
